Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sqlalchemy import Column, Float, MetaData, String, Table

metadata = MetaData()
molecules = Table(
    "molecules",
    metadata,
    Column("name", String, primary_key=True),
    Column("mass", Float),
)

atoms = Table(
    "atoms",
    metadata,
    Column("symbol", String, primary_key=True),
    Column("number", Integer),
)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [13], line 15[0m
[1;32m      3[0m metadata [38;5;241m=[39m MetaData()
[1;32m      4[0m molecules [38;5;241m=[39m Table(
[1;32m      5[0m     [38;5;124m"[39m[38;5;124mmolecules[39m[38;5;124m"[39m,
[1;32m      6[0m     metadata,
[1;32m      7[0m     Column([38;5;124m"[39m[38;5;124mname[39m[38;5;124m"[39m, String, primary_key[38;5;241m=[39m[38;5;28;01mTrue[39;00m),
[1;32m      8[0m     Column([38;5;124m"[39m[38;5;124mmass[39m[38;5;124m"[39m, Float),
[1;32m      9[0m )
[1;32m     11[0m atoms [38;5;241m=[39m Table(
[1;32m     12[0m     [38;5;124m"[39m[38;5;124matoms[39m[38;5;124m"[39m,
[1;32m     13[0m     metadata,
[1;32m     14[0m     Column([38;5;124m"[39m[38;5;124msymbol[39m[38;5;124m"[39m, String, primary_key[38;5;241m=[39m[38;5;28;01mTrue[39;00m),
[0;32m---> 15[0m     Column([38;5;124m"[39m[38;5;124mnumber[39m[38;5;124m"[39m, [43mInteger[49m),
[1;32m     16[0m )

[0;31mNameError[0m: name 'Integer' is not defined
NameError: name 'Integer' is not defined

