Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
results = graph.query(
    """
    SELECT DISTINCT ?asymbol ?bsymbol
    WHERE {
        ?molecule disr:hasElementQuantity ?a .
        ?a disr:countedElement ?elementa .
        ?elementa disr:symbol ?asymbol .
        ?molecule disr:hasElementQuantity ?b .
        ?b disr:countedElement ?elementb .
        ?elementb disr:symbol ?bsymbol
    }
    """
)

for row in results:
    print(f"Elements {row[0]} and %s are found in the same molecule" % row)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[16], line 16[0m
[1;32m      1[0m results [38;5;241m=[39m graph[38;5;241m.[39mquery(
[1;32m      2[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m      3[0m [38;5;124;03m    SELECT DISTINCT ?asymbol ?bsymbol[39;00m
[0;32m   (...)[0m
[1;32m     12[0m [38;5;124;03m    """[39;00m
[1;32m     13[0m )
[1;32m     15[0m [38;5;28;01mfor[39;00m row [38;5;129;01min[39;00m results:
[0;32m---> 16[0m     [38;5;28mprint[39m([38;5;124;43mf[39;49m[38;5;124;43m"[39;49m[38;5;124;43mElements [39;49m[38;5;132;43;01m{[39;49;00m[43mrow[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[38;5;132;43;01m}[39;49;00m[38;5;124;43m and %s are found in the same molecule[39;49m[38;5;124;43m"[39;49m[43m [49m[38;5;241;43m%[39;49m[43m [49m[43mrow[49m)

[0;31mTypeError[0m: not all arguments converted during string formatting
TypeError: not all arguments converted during string formatting

